### ISSUE TITLE
[DL] Shrub billboards incorrectly swizzled

### ISSUE THREAD

**Issue by badger41** [Horizon-Private-Server/horizon-forge-dl#20]
Shrub billboard textures in DL are not appearing correctly, they appear to be swizzled/unswizzled when they need the inverse.

https://github.com/Horizon-Private-Server/horizon-forge/assets/22241322/e36082bb-dc1f-45c3-8b6a-3c68dc7eab5a

**Comment by Dnawrkshp** [comment]
Can you confirm this happens with DL billboard shrubs? I think it might be the importer for UYA/GC shrubs that are being incorrectly swizzled.

**Comment by Dnawrkshp** [comment]
Fixed in v1.1.9 https://github.com/Horizon-Private-Server/horizon-forge/releases/tag/v1.1.9
