### ISSUE TITLE
Material errors when building DZO files

### ISSUE THREAD

**Issue by badger41** [Horizon-Private-Server/horizon-forge-dl#45]
Console is spammed with material errors when attempting to build DZO files for blackwater city. Possibly related to instanced collision materials?

![Unity_wAzzOo7ZPJ](https://github.com/user-attachments/assets/849aec5b-bcb5-4d4c-a54d-431865516bee)

**Comment by badger41** [comment]
I Figured it out, it's because I had an instanced mesh collider for a piece of tfrag that I needed in order to patch a hole in the terrain.

I realized this wasn't actually blocking the dzo build either, but just as an FYI.

**Comment by Dnawrkshp** [comment]
Fixed in e7867899d2fd44276d46a8304438a1d174e07e00
